apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculator.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "calculator.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "calculator.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: calculator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: APP_ENV
              value: {{ .Values.config.APP_ENV | quote }}

            - name: APP_NAME
              value: {{ .Values.config.APP_NAME | quote }}

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | quote }}
                  key: API_KEY

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
